### ISSUE TITLE
Handling multiple domain objects being retreived 

### ISSUE THREAD

**Issue by mickeypuri** [DanWahlin/Observable-Store#1]
Hi Dan, 
Like the keep it simple approach. If your project has say 8 entities, each of which you wish to keep the state for, and each of which can be retreived separately from your back end as well, then am I correct in thinking you will need 8 different Observable Store instances? JSo that each Observable store tracks and maintains state for one particular entity?

Am asking, because if we were to keep all 8 in a single store, then it would mean all our http get / post etc for all 8 entitities would be in the same class, which would become hard to maintain.

Handling this usecase was not clear from the readme hence wanted to ask. thanks.

**Comment by DanWahlin** [comment]
Hi there! With Observable Store only one store will be created to store all 8 entities (singleton). That allows a single store to be created but different services to have single responsibility (good for maintenance of course). For example, you might have the following:

YourStore
   customers property
   orders property
   settings property

CustomerService extends ObservableStore<YourStore>
- Would have functionality to get/set the state for customers

OrdersService extends ObservableStore<YourStore>
- Would have functionality to get/set the state for orders

SettingsService extends extends ObservableStore<YourStore>
- Would have functionality to get/set the state for settings

All 3 share the same store but only update what they're responsible for (customers, orders, settings respectively).

Your HTTP calls can now be separated into different services to keep things clean, but all 3 services would be interacting with the same store instance when they call setState() or getState(). Anyone that subscribes to state changes in a service such as SettingsService would only get changes that service caused in the store (changes to settings in this example). The same would apply to the other services.

Hope that helps.

**Comment by mickeypuri** [comment]
That really helped. Once I saw that the state object was being held as a singleton via a closure in the ObservableStore class, then it all became clear. Thanks.

**Comment by DanWahlin** [comment]
Awesome - have fun with it!

**Comment by mickeypuri** [comment]
Thanks! I had a deep dive into it, and have spotted a way of enhancing. Think it would benefit other users too. Would it be ok, if I were to submit a pull request?

**Comment by DanWahlin** [comment]
Absolutely. I'll have to take a look at it of course before accepting since my overall goal is to keep things super simple, but I'm definitely open to enhancements if they'll benefit others. Just depends on what is being done.

**Comment by mickeypuri** [comment]
Fantastic, thank you. Yes of course I totally understand, and simplicity is my goal too and what I really liked about your approach. Will jump on it this weekend. Hopefully you will like it.

**Comment by DanWahlin** [comment]
Sounds good. If you want to chat about it at all before you put in the time I'm happy to do that here. This is one of those projects where I don't plan to add much more feature-wise (as mentioned) just to keep things simple. But, I'm always open to hearing about new ideas. :-)

**Comment by mickeypuri** [comment]
I don't appear to be getting message notifications from github, so afraid I've only just now seen your message. In fact, I've already made a new feature branch and have put the code on it and its fully ready. I have been trying to push to your repository but it is not allowing me. Its erroring with:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/DanWahlin/Observable-Store.git/'
I've changed my password just in case, but its not made any difference. Is there some setting on your repo which is stopping me from pushing a branch to it, or do you need to perhaps add me as a contributor before it will allow me to push the branch?

**Comment by mickeypuri** [comment]
I've just read a bit on github, I need to be added to collaborators to be able to push a branch to the repo.

**Comment by DanWahlin** [comment]
Hi Mickey. I wouldn't want a new branch showing up actually. I'm OK with looking at a pull request though.

**Comment by mickeypuri** [comment]
Hi Dan, Sorry I haven't contributed for some time now and am forgetting the approach. Should I create and push to my own repo and then do a pull request from there?

**Comment by DanWahlin** [comment]
Once you've cloned it you can work locally and then submit a pull request back to this repository. Here's a post that shows several options:

https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

But, before you go to the trouble to do that, let me know what you're planning. I don't want you to go to the trouble to do it only to later tell you, "Thanks - but not interested in that". I'm definitely interested in hearing about it first if possible. I'm just not looking to expand this particular repository much as mentioned and want to respect your time as well.

**Comment by mickeypuri** [comment]
Totally understand, and thanks. However I've already fully coded it up, and also updated the readme. So the most efficient would now be to simply create the pull request. then you could have a look. And if you feel its not for you, then its totally fine, no issues whatsoever. However as I am planning on using it for myself at work, and I wanted this, I thought I should share it too and give something back to the community too. :)

**Comment by DanWahlin** [comment]
Sounds great! Looking forward to seeing it.

**Comment by mickeypuri** [comment]
Thanks, I've just created the pull request. Looking forward to hearing what you think of it.

**Comment by DanWahlin** [comment]
Awesome - thanks. Just read the general idea and I really like it. I'll have to spend more time on it when I can though and make sure it doesn't impact the existing API at all. Slammed with a project right now but once I come up for air I'll take a closer look. Thanks again!

**Comment by mickeypuri** [comment]
Thank you so much for accepting the pull request, and thank you too for your kind words in the version history. Much appreciated!

Yes, I did it so that its completely backwards compatible. Speaking personally, I would really not be amused if anyone put in a breaking change, so that was super important to me.

I'll be very pleased to feedback on a blog post, and will watch out for a tweet on it. I've used Redux previously and so can add my perspective from that too.

**Comment by DanWahlin** [comment]
Here's the post I mentioned:

https://blog.codewithdan.com/simplifying-front-end-state-management-with-observable-store/

I'm being careful not to call out a specific pattern in the post since every scenario is different (and we all have a million viewpoints on state management). But, if you have time to add a comment at the bottom about your experience with various options that'd be awesome!

**Comment by mickeypuri** [comment]
Thanks I'll certainly have a look at the blog post and will definitely add a comment.

Thanks for spotting and fixing the property name in settingsDefaults. I first went with underscores in the property name in the interface, and then later thought it needs to be camel cased, and did a variable name change in the interface using the IDE, which of course missed the property in the settingsDefaults, so thanks again for fixing that.

**Comment by DanWahlin** [comment]
Appreciate it - thanks Micky!
