### ISSUE TITLE
Weird store structure when using stateSliceSelector

### ISSUE THREAD

**Issue by orosro** [DanWahlin/Observable-Store#116]
Issue

When I'm using the StateSliceSelector along the reduxExtension I see some weird behavior regarding the store. Depending on the moment I call setState, the store is updated but with a different structure:

```
export class RegistryService extends ObservableStore<StoreState> {
	constructor() {
		super({
			trackStateHistory: true,
			stateSliceSelector: (state) => state && state[ProRegistryStoreName],
		});
		logger.log('REGISTRY', 'Initialize registry service');

		this.setStoreInitialState();
	}
}
```

```
private setStoreInitialState(): void {
		const initialState = {
			[ProRegistryStoreName]: {
				'test': 'test',
				[ProRegistryEnum.publicApps]: [],
				[ProRegistryEnum.privilegedApps]: [],
			},
		};
		this.setState(initialState, 'INITIALIZE_REGISTRY_STATE');
	}
```

SaveApplications is called from other 2 methods

```
private saveApplications(type: ProRegistryEnum, applications: ApplicationConfig[], storeAction: ProteanStoreActions): void {
		const state = this.getState(); // We need to cast it as any because it will break when setting the state
		state[type] = applications;
		const newState = Object.assign({}, state, {
			[ProRegistryStoreName]: {
				[type]: applications,
			},
		});

		this.setState(newState, storeAction);
	}
```

If I don't use the stateSliceSelector option in my constructor everything seems to work fine but would like to be able to use it as I have multiple sections in my store and I want them separated and I'm also listening for specific store changes on those sections.

```
this.registryService.stateChanged.subscribe( ... do something here)
```
I expect that the above should be called only when that part of the store is updated, which works only with the stateSliceSelector, right? 

I'm not sure if this is an issue or not, but the store doesn't seem right.

![withoutStateSliceSelector](https://user-images.githubusercontent.com/24509132/112876666-72e1de80-90ce-11eb-91ef-d79f5adba5f1.JPG)
![withStateSliceSelector](https://user-images.githubusercontent.com/24509132/112876671-737a7500-90ce-11eb-9dcb-9ed29ced04fa.JPG)
![next step](https://user-images.githubusercontent.com/24509132/112877372-598d6200-90cf-11eb-97ca-fd4e959d24a0.JPG)

**Comment by DanWahlin** [comment]
Thanks for the information @orosro. The Redux DevTools functionality for Observable Store is fairly experimental at this point so I'd first want to make sure that your store state is OK (the raw store - not what's shown in the devtools chart). If the store itself has a problem, then that's definitely an issue that would need to be addressed. Let me know.

If it's just the devtools chart, then let me know if you have the ability to put together a simple demo that illustrates the issue. That would help narrow down what may be going on.

**Comment by DanWahlin** [comment]
I'd need a demo to work through this. I'm closing this for now since I haven't heard back but feel free to open another one if you are able to get a demo together.
