### ISSUE TITLE
It would help so much if you included a fully working react example

### ISSUE THREAD

**Issue by SailingSteve** [DanWahlin/Observable-Store#171]
The line `this.storeSub = CustomersStore.stateChanged.subscribe(state => {` fails in React, with a 

`Header.jsx:61 Uncaught TypeError: Cannot read property 'subscribe' of undefined at Header.componentDidMount (Header.jsx:61)`

And WebStorm reports 'Instance member is not accessible' for stateChanged

I keep looking at your example code and wondering what code is there outside of the snippet, and if the lack of something "obvious" is causing my problem.

It would be so helpful if you provided a JSFiddle or code sandbox.

**Comment by DanWahlin** [comment]
I'd need to know what sample you're running. Your own or the one in the samples folder? I ran that sample (https://github.com/DanWahlin/Observable-Store/tree/main/samples/react-store) and don't see that problem. If you can provide more details that would be helpful.

**Comment by SailingSteve** [comment]
Thanks for the instant reply!  My mistake, I will dig through your sample.  That link to the sandbox would be great on the readme pages.
