### ISSUE TITLE
Using state in synchronous manner

### ISSUE THREAD

**Issue by hamidh2** [DanWahlin/Observable-Store#172]
Is there a way to use the state of a class in a synchronous way because there is a limitation in some places in angular for using asynchronous value and we should provide the data with synchronous methods for instance we should provide such thing in interceptors, I tried to get rid of state asynchronous behavior with a trick but it didn't work 
I created a method in my state class and I tend to call it in other places but it always returns the default value!!!
plz help to overcome this issue
  ```
  public getUserState(): UserState | null {
    const state = this.getState();
    console.log('state in auth service', state);
    if (state && state.currentUser) {
      return state;
    }
    return null;
  }
```
FYI @DanWahlin

**Comment by DanWahlin** [comment]
Please combine this with the other issue you added where I asked for a demo. I'll need that to look into it more.
