### ISSUE TITLE
Rx.js 7.2 migration and compatibility?

### ISSUE THREAD

**Issue by JasonLandbridge** [DanWahlin/Observable-Store#174]
Currently having installed rx.js version 7.2 prevents the updating of observable-store.

Are there plans to upgrade or can I make a pull-request?

![image](https://user-images.githubusercontent.com/15127381/125210191-6f99e980-e29e-11eb-87b9-c1a45f94925e.png)

**Comment by DanWahlin** [comment]
Thanks for asking about this Jason. There's always a battle with that version but I'd like to get this working for you. I'm thinking about the following for the peerDependency version. Thoughts?

```json
"peerDependencies": {
  "rxjs": ">=6.4.0 <8"
}
```

**Comment by DanWahlin** [comment]
I just pushed out a new package that does what I mentioned above (no other changes). Should be good to go for your scenario but let me know if you hit any issues.

**Comment by JasonLandbridge** [comment]
Hey Dan, thanks for the quick response and fix! To be honest, I think the error was my fault because I was upgrading all my NPM packages at once. Everything went smoothly after going through each package one by one. 

I have updated to the new version and found everything to still be working with rx.js 7.2.0 and your change looks like a good fix. I'm currently fixing my docker deployment workflow and no problems there either when using a fresh `npm install`. 

All seems good, thanks!

**Comment by DanWahlin** [comment]
Excellent! Thanks for the update.
