### ISSUE TITLE
Can't run Angular samples

### ISSUE THREAD

**Issue by trentsteel84** [DanWahlin/Observable-Store#46]
I've tried all 4 Angular samples and after running 'ng serve -o' i'm getting errors in the terminal.
For example, in the angular-store-edits sample, i'm getting the following:

ERROR in C:/Repos/Observable-Store/modules/observable-store/index.ts
Module not found: Error: Can't resolve 'tslib' in 'C:\Repos\Observable-Store\modules\observable-store'
ERROR in C:/Repos/Observable-Store/modules/observable-store/observable-store.ts
Module not found: Error: Can't resolve 'tslib' in 'C:\Repos\Observable-Store\modules\observable-store'
ERROR in C:/Repos/Observable-Store/modules/observable-store/observable-store-base.ts    
Module not found: Error: Can't resolve 'tslib' in 'C:\Repos\Observable-Store\modules\observable-store'
ERROR in C:/Repos/Observable-Store/modules/observable-store-extensions/index.ts
Module not found: Error: Can't resolve 'tslib' in 'C:\Repos\Observable-Store\modules\observable-store-extensions'
ERROR in C:/Repos/Observable-Store/modules/observable-store-extensions/redux-devtools.extension.ts
Module not found: Error: Can't resolve 'tslib' in 'C:\Repos\Observable-Store\modules\observable-store-extensions'
ERROR in C:/Repos/Observable-Store/modules/observable-store-extensions/angular/angular-devtools-extension.ts
Module not found: Error: Can't resolve 'tslib' in 'C:\Repos\Observable-Store\modules\observable-store-extensions\angular'
ERROR in C:/Repos/Observable-Store/modules/observable-store/utilities/cloner.service.ts 
Module not found: Error: Can't resolve 'tslib' in 'C:\Repos\Observable-Store\modules\observable-store\utilities'

I've tried deleting the node modules folder and installing the npm packages again, but that didn't make a difference.

However if i hard-reset back to commit dd4a118883453f8bcca989edd9c2f4e1f1aa6f0d then it's working fine.

**Comment by DanWahlin** [comment]
Thanks for letting me know about this issue. I modify tsconfig.json for each sample project to do local package testing and forgot to comment out that path before pushing the project to Github. To make it work you would've had to run npm install in each of the folders in `modules` (which you shouldn't have to do of course and wouldn't have known to do). My bad on that.

If you grab the latest version of the repo things should be back to normal now. Thanks again.
