### ISSUE TITLE
Redux Extension throws runtime error in angular prod build

### ISSUE THREAD

**Issue by riscie** [DanWahlin/Observable-Store#48]
I am getting the following runtime error in my angular production build, when I add the redux devtools according to the `README.md`:

```
TypeError: Cannot read property 'send' of undefined
  at e.sendStateToDevTool (/main-es2015.e6b3fec3e40857a99079.js:1:665719)
  at l._next (/main-es2015.e6b3fec3e40857a99079.js:1:665456)
  at l.__tryOrUnsub (/main-es2015.e6b3fec3e40857a99079.js:1:184374)
  at l.next (/main-es2015.e6b3fec3e40857a99079.js:1:183595)
  at c._next (/main-es2015.e6b3fec3e40857a99079.js:1:182766)
...
```
I reckon this is because the devtools do not exist in the prod build.
I therefore changed my `main.ts` to the following:

**main.ts**
```typescript
// ...
import { ReduxDevToolsExtension } from '@codewithdan/observable-store-extensions';
// ...
if (!environment.production) {
    ObservableStore.addExtension(new ReduxDevToolsExtension());
}
```

Should this be added to the docs, or is there another way this should be handled? I could make a quick pr if it helps.

**Comment by DanWahlin** [comment]
Thanks for reporting it. That’s a known issue that we hit that was recently fixed. I’m hoping to get the update out in the next few days. 

Your solution is a good workaround for now especially since you likely won’t want the extension added for production build anyway (aside possibly debugging and issue that comes up).

**Comment by DanWahlin** [comment]
Also, thanks for the suggestion on the docs. I’ll add something about that for production as well.

**Comment by riscie** [comment]
Thank you again for the quick answer!

**Comment by DanWahlin** [comment]
I just pushed out the update so that issue should be fixed now with the latest packages. But, if you do have any additional problems let me know.
