### ISSUE TITLE
Super() Expected 1 argument but got 2

### ISSUE THREAD

**Issue by ChrisAllisonMalta** [DanWahlin/Observable-Store#5]
Hi, 

Looks like an interesting library which I'm investigating for a project.

I get an error on the super() call below when I try to run the sample saying that it 

> Expected 1 argument but got 2

```
constructor() {
        const initialState = {
            customers: [],
            customer: null
        }
        super(initialState, { trackStateHistory: true });
    }
```

**Comment by DanWahlin** [comment]
Thanks Chris - not sure why that error is showing. Can you let me know which sample you're running?

**Comment by ChrisAllisonMalta** [comment]
Actually I was just creating a new app with NG new and copying in the code from the readme

**Comment by DanWahlin** [comment]
Thanks for the info. Did you run the `npm install @codewithdan/observable-store` command and then derive your service class from ObservableStore? I'd have to see more to help on this one.

**Comment by ChrisAllisonMalta** [comment]
Hi Dan, Yeah I did, it was pretty much from a NG new project too, I've not had a chance to create a test project to share

**Comment by DanWahlin** [comment]
Ok. Let me know. The samples in the Github project should help too.

**Comment by jasonkoon** [comment]
I get same problem.  ObservableStore constructor takes only 1 argument but the readme text shows 2.  The samples only use 1.
angular-store-edits sample customers.service:
 super({ trackStateHistory: true, logStateChanges: true });

The ReadMe is out of date,  showing a 2 parameter constructor being used:
`const initialState = {
            customers: [],
            customer: null
        }
        super(initialState, { trackStateHistory: true });`

The sample accomplishes the same thing by calling setState directly after the call to super()

**Comment by DanWahlin** [comment]
Sorry folks. Sounds like that's totally on me. I forgot about the readme update (and that we simplified the constructor). I'll get that updated soon though.

**Comment by jasonkoon** [comment]
no problem, Thanks for the library.  The samples are great, and are the better getting started guide anyway.

**Comment by DanWahlin** [comment]
Thanks. My apologies @chrisallisonmalta for not realizing the docs were out of sync. I've been using the project for over a year with two constructor parameters and wasn't thinking about the change that was made to simplify it to one parameter (old habits die hard I guess). Thanks @jasonkoon for reminding me. :-)

**Comment by DanWahlin** [comment]
Updated the readme

**Comment by ChrisAllisonMalta** [comment]
Thanks @DanWahlin
