### ISSUE TITLE
Reset all states of all stores.

### ISSUE THREAD

**Issue by LuizFilipeMedeira** [DanWahlin/Observable-Store#51]
Hi Dan,  I need to reset all states when user logout. What would be the best way to achieve this ?

**Comment by DanWahlin** [comment]
Hi Luiz. In the logout functionality you can inject any service that derives from `ObservableStore<T>` and then call `setState(yourDesiredState, 'RESET_STORE')` from within the service (pass null, {}, or an initialized store state to it). 

If you're tracking state history you might also want to call `resetStateHistory()`from within the service (unless you want it to be kept around).

**Comment by LuizFilipeMedeira** [comment]
I thought about it, but doing it for several services would not be good, I would have to inject them all.
ObservableStore offers allStoreServices, which let me loop through all services,  with that I could do: 

class ObservableStoreWrapper<T> extends ObservableStore<T> {
  public clearState(): void {
    this.setState(null);
  }
}

 and then in the logout call: 

ObservableStore.allStoreServices.forEach((it: ObservableStoreWrapper<any>) => {
      it.clearState();
    });

Maybe the ObservableStore could have a function for that, whose implementation was not mandatory, or a static method to clean all services at the same time.
What do you think ?

**Comment by DanWahlin** [comment]
You only have to have a reset in one service. All services share the same singleton store.

**Comment by DanWahlin** [comment]
I'm going to close this but if you have any other questions feel free to post them here.

**Comment by DanWahlin** [comment]
As an update, I'm going to add an `ObservableStore.resetState()` static function into it. Someone else needed that for testing purposes and it would also apply to what you asked about as well. You'll be able to use it to pass any value (such as null or a full object) to the store.

You can find out more about it i the readme:

https://github.com/danwahlin/observable-store#store-api

I'm hoping to get the package update pushed out this weekend.
