### ISSUE TITLE
How to set the initial state?

### ISSUE THREAD

**Issue by alexsanzdev** [DanWahlin/Observable-Store#58]
Hi Dan,

In the current version, the state is null/undefined until the state is set. What's the best way to set an initial state for a store?

Right now I'm doing this:
```javascript
  constructor() {
    this.setState({}, 'INITIALIZE_STATE');
  }
```
However, I'm not sure this is semantically correct or just a workaround. Feels wrong somehow, because there was no action triggered - it's just the state being initialized (not an action imho).

Maybe a `setInitialState` or `initializeState` method is necessary.
```javascript
  constructor() {
    this.setInitialState({});
  }
```
Or maybe in the super constructor since initializing state would be done only once?
```javascript
  constructor() {
    this.super({});
  }
```
However, that is already used for the config/settings...

Any thoughts on this?

**Comment by DanWahlin** [comment]
You’ll want to use the ObservableStore.initalizeState() static function:

https://github.com/DanWahlin/Observable-Store/blob/master/README.md#store-api

**Comment by alexsanzdev** [comment]
Oh, I missed the important detail that it is **one** global state. Since there's multiple stores I got the impression that there are **multiple isolated states** as well (one per store). This means that you need to be careful not to overwrite other stores data, right? What would be the best way to not overwrite other stores data? Partitioning/slicing by key, like in Redux?

**Comment by DanWahlin** [comment]
Only one store which is pretty typical. Some state management solutions do allow multiple stores, but with services extending Observable Store they should each be single responsibility anyway so there shouldn't be an issue with one service overwriting data from another. If there is a problem there then I'd argue the architecture needs to be reconsidered. We have several large apps using it now and that hasn't been an issue at all, but our services have that single responsibility focus. 

Having said that, I may consider allowing multiple stores in the future. The main goal as of today though is to keep it really simple to work with so I'm trying hard not to pollute the API with much more. :-)

**Comment by alexsanzdev** [comment]
Thanks for the quick reply Dan! Yes, I agree with you. I prefer single state. Previously I used MobX where you could have multiple stores, but this became a problem when replaying in redux devtools.

Ok so the key here is "single responsibility" - I'll keep that in mind, thanks.

Agree, please don't add features that changes the basic concept :) I really appreciate the simplicity of this lib. This is what separate this one from the other libraries (at least the ones I tried: redux, MobX, Akita).

**Comment by DanWahlin** [comment]
Sound great. I'm super open to feature ideas (many have come from other people using it) so if you do think of something and it still keeps things simple let me know. Appreciate it!
