### ISSUE TITLE
API suggestion: state$ instead of stateChanged

### ISSUE THREAD

**Issue by alexsanzdev** [DanWahlin/Observable-Store#59]
Have you considered using `state$` instead of `stateChanged` for the observable? I think it would be more intuitive for two reasons.

1. Even if the suffix **$** is not a standard, it is used by most developers and libraries using Observables/RxJs. It's widely understood that this variable/property is an observable (or stream of updates if you will). For example the popular library UI-Router uses it for state (_state$_) and param (_param$_) updates.

2. `stateChanged` sounds like we are dealing with an event (state change event) rather than the state itself. To my understanding this is not an event, right? It's the observable state (i.e. the observable version of getState()). An event would be a subset/superset or completely different structure, but this is not the case if I understand correctly - it's a 1:1 mapping. If this is correct it should be called just `state`, imho.

**Comment by DanWahlin** [comment]
Hi Alex. At this point it would be challenging to change the API. While I personally like something like state$ (we use $ in our projects), not everyone does I've found and people who are new to the observable world still understand the "changed" concept. It could be introduced without breaking the API of course, but increasing the surface area is something I want to avoid. Another challenge is there are 4 observable properties currently (stateWithPropertyChanges and the "global" ones) which means they'd all have to be renamed.

Having said that, when v3 rolls around someday it's something that could be added and the existing ones could be deprecated. I can't make any promises there but appreciate the suggestion.
