### ISSUE TITLE
Issue in README.md

### ISSUE THREAD

**Issue by adibro500** [DanWahlin/Observable-Store#7]
existing readme:     
```
add(customer: Customer) {
            let state = this.getState();
            state.customers.push(customer);
            this.setState({ customers: state.customers }, 'add_customer');
        }

        remove() {
            let state = this.getState();
            state.customers.splice(state.customers.length - 1, 1);
            this.setState({ customers: state.customers } 'remove_customer');
        }
        
        sort(property: string = 'id') {
            let state = this.getState();
            const sortedState = this.sorterService.sort(state.customers, property);
            this.setState({ customers: sortedState } 'sort_customers');
        }
```
Expected readme: 
   ```
 add(customer: Customer) {
            let state = this.getState();
            state.customers.push(customer);
            this.setState({ customers: state.customers }, 'add_customer');
        }

        remove() {
            let state = this.getState();
            state.customers.splice(state.customers.length - 1, 1);
            this.setState({ customers: state.customers }, 'remove_customer');
        }
        
        sort(property: string = 'id') {
            let state = this.getState();
            const sortedState = this.sorterService.sort(state.customers, property);
            this.setState({ customers: sortedState }, 'sort_customers');
        }
```
I may sound silly but just thought you should know, Thanks

**Comment by DanWahlin** [comment]
Can you highlight the difference you're trying to point out for me? I'm not seeing it. Out on vacation and on my phone so may be missing it.

**Comment by adibro500** [comment]
![image](https://user-images.githubusercontent.com/25535374/57707550-72c8c900-7685-11e9-9a90-941687ec6027.png)

**Comment by adibro500** [comment]
![image](https://user-images.githubusercontent.com/25535374/57707674-a1df3a80-7685-11e9-8678-863156ae561e.png)

**Comment by BigAB** [comment]
I believe 
@adibro500 is referring to the missing comma's in the `setState()` calls in `.remove()` and `.sort()` 


<img width="855" alt="Screen Shot 2019-05-20 at 2 27 08 PM" src="https://user-images.githubusercontent.com/76821/58050077-9bc8de00-7b0b-11e9-94b8-01cbe9241e2a.png">

**Comment by DanWahlin** [comment]
Thanks @BigAB and @adibro500. Been out on vacation so viewing all this on my phone (definitely didn't notice the missing commas on the smaller screen) but will get it updated. Appreciate it!
