### ISSUE TITLE
ObservableStore cannot be found

### ISSUE THREAD

**Issue by AndonMitev** [DanWahlin/Observable-Store#8]
Hello i have following issue: when i try to extend the class **ObservableStore**, angular complains that cannot be found.
![image](https://user-images.githubusercontent.com/32274987/57653581-d649ec80-75da-11e9-8f1c-15b17674ff7f.png)
"@codewithdan/observable-store": "^1.0.19", i got this one in my package.json but still cannot be seen by my angular

**Comment by DanWahlin** [comment]
It looks like you're missing the import at the top of the file:

import { ObservableStore } from '@codewithdan/observable-store';
