### ISSUE TITLE
README.md Angular Sample Incorrect

### ISSUE THREAD

**Issue by jkyoutsey** [DanWahlin/Observable-Store#9]
```typescript
    ngOnInit() {
        // If using async pipe
        // this.customers$ = this.customersService.stateChanged;
```
![image](https://user-images.githubusercontent.com/3846466/58045276-95d0fe00-7b07-11e9-8d8a-7ea8c6130b98.png)

Tried submitting a PR for it, but no privs :D 

The whole project is remarkably simple.  I can see how this would end up with a much simpler approach to state management!

**Comment by DanWahlin** [comment]
Thanks Jared! I'll get that updated.
