### ISSUE TITLE
How do I subscribe to only changes

### ISSUE THREAD

**Issue by Godrules500** [DanWahlin/Observable-Store#91]
I am trying to subscribe to changes only and not when initially subscribed.  How can I not have the stage changed triggered when initially subscribed?

Thanks for your help!

**Comment by orosro** [comment]
store.stateChanged.pipe(skip(1)).subscribe(...)

**Comment by DanWahlin** [comment]
That looks like a viable option. Have you tried the `stateWithPropertyChanges` option? Not sure if it'd help in your case but it scopes the changes more.

https://github.com/DanWahlin/Observable-Store#store-api

If what you mention above gets the job done for you we'll close out the issue though.

**Comment by Godrules500** [comment]
Thanks guys!
