### ISSUE TITLE
Losing Class (getters/setters) when returning object from store

### ISSUE THREAD

**Issue by Godrules500** [DanWahlin/Observable-Store#95]
When I create a class (with getters/setters) all is well. When I store it in the store and retrieve it however, it is returning as an object and thus have loss the class getters/setters. Is there a way to store or retrieve it so that it maintains the class?

**Comment by DanWahlin** [comment]
Observable Store only stores data. Everything stored has to be serializable to JSON so getters/setters, functions, etc. won't be preserved.
