### ISSUE TITLE
setState() does not update property when setting to undefined

### ISSUE THREAD

**Issue by jornetsimon** [DanWahlin/Observable-Store#96]
This call
```typescript
this.setState({ user: undefined });
```
does register an event but does not assign `undefined` to the state property.

But
```typescript
this.setState({ user: null });
```
sets user to `null` properly.

[Simple StackBlitz reproduction here.](https://stackblitz.com/edit/observable-store-undefined?file=src%2Fapp%2Fapp.component.ts)

**Is this the intended behavior?**

**Comment by DanWahlin** [comment]
That's expected behavior. JSON doesn't support undefined but does support null values.
