### ISSUE TITLE
How to store n number of propertes (making the state properties dynamic)

### ISSUE THREAD

**Issue by Godrules500** [DanWahlin/Observable-Store#97]
I have a situation where I have many pricing scenarios that can be applied to a job.  Because of this I was going to create an object that looked like StoreState{PricingCalculationInfo:{ [name: string]: PricingCalculationInfo }}.  However, because I am reusing a bunch of components, any time that PricingCalculationInfo object changes, every scenario would then run through all of their subscriptions again, which I don't need to happen.

Because of this, unless there is a way for me to tell which property of PricingCalcInfo changed, I am going to need a list of dynamic store state properties.  Each scenario would then need its' own StoreState that it can subscribe to (or at least exclude all changes except when that scenario's state changes).

Is this possible to make the store state properties a little more dynamic?

**Comment by DanWahlin** [comment]
Check out the **stateWithPropertyChanges** property. It allows you to see specific properties that changed.

`Subscribe to store changes in the particlar slice of state updated by a Service and also include the properties that changed as well. Upon subscribing to stateWithPropertyChanges you will get back an object containing state (which has the current slice of store state) and stateChanges (which has the individual properties/data that were changed in the store).`

https://github.com/danwahlin/observable-store#store-api

The https://github.com/DanWahlin/Observable-Store/blob/7811aec717/samples/angular-stateChanged/src/app/app.component.ts example shows a simple demo of it in action and what it gives you.
